# Licensed under a 3-clause BSD style license - see LICENSE.rst
# -*- coding: utf-8 -*-
from __future__ import absolute_import, division, print_function, unicode_literals
# The line above will help with 2to3 support.
def get_product_version(options):
    """Determine the base product and version information.

    Parameters
    ----------
    options : Namespace
        Options object generated by argparse.

    Returns
    -------
    get_product_version : tuple
        A tuple containing the base product name and version.
    """
    import logging
    from os.path import basename
    from . import known_products
    logger = logging.getLogger(__name__)
    if '/' in options.product:
        fullproduct = options.product
        baseproduct = basename(options.product)
    else:
        try:
            fullproduct = known_products[options.product]
            baseproduct = options.product
        except KeyError:
            logger.error("Could not determine the exact location of {0}!".format(options.product))
            raise
    baseversion = basename(options.product_version)
    return (fullproduct, baseproduct, baseversion)
